// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "estimate_FR.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic estimate_FR::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic estimate_FR::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> estimate_FR::ap_ST_fsm_state1 = "1";
const sc_lv<9> estimate_FR::ap_ST_fsm_state2 = "10";
const sc_lv<9> estimate_FR::ap_ST_fsm_state3 = "100";
const sc_lv<9> estimate_FR::ap_ST_fsm_state4 = "1000";
const sc_lv<9> estimate_FR::ap_ST_fsm_state5 = "10000";
const sc_lv<9> estimate_FR::ap_ST_fsm_state6 = "100000";
const sc_lv<9> estimate_FR::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> estimate_FR::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> estimate_FR::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> estimate_FR::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> estimate_FR::ap_const_lv32_1 = "1";
const sc_lv<1> estimate_FR::ap_const_lv1_0 = "0";
const sc_lv<32> estimate_FR::ap_const_lv32_2 = "10";
const sc_lv<1> estimate_FR::ap_const_lv1_1 = "1";
const sc_lv<32> estimate_FR::ap_const_lv32_3 = "11";
const sc_lv<32> estimate_FR::ap_const_lv32_7 = "111";
const sc_lv<8> estimate_FR::ap_const_lv8_0 = "00000000";
const sc_lv<32> estimate_FR::ap_const_lv32_8 = "1000";
const sc_lv<21> estimate_FR::ap_const_lv21_0 = "000000000000000000000";
const sc_lv<64> estimate_FR::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<7> estimate_FR::ap_const_lv7_0 = "0000000";
const sc_lv<21> estimate_FR::ap_const_lv21_1999 = "1100110011001";
const sc_lv<8> estimate_FR::ap_const_lv8_C8 = "11001000";
const sc_lv<8> estimate_FR::ap_const_lv8_1 = "1";
const sc_lv<7> estimate_FR::ap_const_lv7_4B = "1001011";
const sc_lv<7> estimate_FR::ap_const_lv7_1 = "1";
const sc_lv<16> estimate_FR::ap_const_lv16_0 = "0000000000000000";
const sc_lv<161> estimate_FR::ap_const_lv161_lc_1 = "101000000000001111000000000101101000000010000111000000110010101000010010111111001";
const sc_lv<10> estimate_FR::ap_const_lv10_0 = "0000000000";
const sc_lv<64> estimate_FR::ap_const_lv64_1 = "1";
const sc_lv<32> estimate_FR::ap_const_lv32_5D = "1011101";
const sc_lv<32> estimate_FR::ap_const_lv32_64 = "1100100";
const sc_lv<22> estimate_FR::ap_const_lv22_1999 = "1100110011001";
const bool estimate_FR::ap_const_boolean_1 = true;

estimate_FR::estimate_FR(sc_module_name name) : sc_module(name), mVcdFile(0) {
    estimate_FR_mul_80ns_82ns_161_5_1_U1 = new estimate_FR_mul_80ns_82ns_161_5_1<1,5,80,82,161>("estimate_FR_mul_80ns_82ns_161_5_1_U1");
    estimate_FR_mul_80ns_82ns_161_5_1_U1->clk(ap_clk);
    estimate_FR_mul_80ns_82ns_161_5_1_U1->reset(ap_rst);
    estimate_FR_mul_80ns_82ns_161_5_1_U1->din0(grp_fu_181_p0);
    estimate_FR_mul_80ns_82ns_161_5_1_U1->din1(grp_fu_181_p1);
    estimate_FR_mul_80ns_82ns_161_5_1_U1->ce(ap_var_for_const0);
    estimate_FR_mul_80ns_82ns_161_5_1_U1->dout(grp_fu_181_p2);
    estimate_FR_mul_mul_8ns_14ns_22_1_1_U2 = new estimate_FR_mul_mul_8ns_14ns_22_1_1<1,1,8,14,22>("estimate_FR_mul_mul_8ns_14ns_22_1_1_U2");
    estimate_FR_mul_mul_8ns_14ns_22_1_1_U2->din0(mul_ln1118_fu_242_p0);
    estimate_FR_mul_mul_8ns_14ns_22_1_1_U2->din1(mul_ln1118_fu_242_p1);
    estimate_FR_mul_mul_8ns_14ns_22_1_1_U2->dout(mul_ln1118_fu_242_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_FR_V_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln14_fu_237_p1 );

    SC_METHOD(thread_FR_V_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_FR_V_d0);
    sensitive << ( trunc_ln_reg_294 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_FR_V_we0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_add_ln8_fu_130_p2);
    sensitive << ( r_V_reg_92 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_136_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_136_p2 );

    SC_METHOD(thread_count_V_fu_205_p2);
    sensitive << ( t_V_2_reg_103 );

    SC_METHOD(thread_grp_fu_181_p0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( grp_fu_181_p00 );

    SC_METHOD(thread_grp_fu_181_p00);
    sensitive << ( t_V_fu_169_p3 );

    SC_METHOD(thread_grp_fu_181_p1);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_icmp_ln1496_fu_195_p2);
    sensitive << ( zext_ln8_reg_248 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( shl_ln_fu_187_p3 );

    SC_METHOD(thread_icmp_ln1497_fu_200_p2);
    sensitive << ( mul_ln1118_reg_266 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( shl_ln_fu_187_p3 );

    SC_METHOD(thread_icmp_ln8_fu_136_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_V_reg_80 );

    SC_METHOD(thread_icmp_ln9_fu_152_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_115 );

    SC_METHOD(thread_j_fu_158_p2);
    sensitive << ( j_0_reg_115 );

    SC_METHOD(thread_mul_ln1118_fu_242_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( mul_ln1118_fu_242_p00 );

    SC_METHOD(thread_mul_ln1118_fu_242_p00);
    sensitive << ( tmp_V_2_fu_142_p2 );

    SC_METHOD(thread_mul_ln1118_fu_242_p1);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_select_ln10_fu_211_p3);
    sensitive << ( t_V_2_reg_103 );
    sensitive << ( icmp_ln1497_fu_200_p2 );
    sensitive << ( count_V_fu_205_p2 );

    SC_METHOD(thread_select_ln1496_fu_219_p3);
    sensitive << ( t_V_2_reg_103 );
    sensitive << ( icmp_ln1496_fu_195_p2 );
    sensitive << ( select_ln10_fu_211_p3 );

    SC_METHOD(thread_shl_ln_fu_187_p3);
    sensitive << ( spksTime_V_q0 );

    SC_METHOD(thread_spksTime_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln10_fu_164_p1 );

    SC_METHOD(thread_spksTime_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_t_V_fu_169_p3);
    sensitive << ( t_V_2_reg_103 );

    SC_METHOD(thread_tmp_V_2_fu_142_p2);
    sensitive << ( tmp_V_reg_80 );

    SC_METHOD(thread_zext_ln10_fu_164_p1);
    sensitive << ( j_0_reg_115 );

    SC_METHOD(thread_zext_ln14_fu_237_p1);
    sensitive << ( tmp_V_reg_80 );

    SC_METHOD(thread_zext_ln8_fu_126_p1);
    sensitive << ( r_V_reg_92 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln8_fu_136_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln9_fu_152_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "estimate_FR_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, spksTime_V_address0, "(port)spksTime_V_address0");
    sc_trace(mVcdFile, spksTime_V_ce0, "(port)spksTime_V_ce0");
    sc_trace(mVcdFile, spksTime_V_q0, "(port)spksTime_V_q0");
    sc_trace(mVcdFile, FR_V_address0, "(port)FR_V_address0");
    sc_trace(mVcdFile, FR_V_ce0, "(port)FR_V_ce0");
    sc_trace(mVcdFile, FR_V_we0, "(port)FR_V_we0");
    sc_trace(mVcdFile, FR_V_d0, "(port)FR_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zext_ln8_fu_126_p1, "zext_ln8_fu_126_p1");
    sc_trace(mVcdFile, zext_ln8_reg_248, "zext_ln8_reg_248");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln8_fu_130_p2, "add_ln8_fu_130_p2");
    sc_trace(mVcdFile, add_ln8_reg_253, "add_ln8_reg_253");
    sc_trace(mVcdFile, tmp_V_2_fu_142_p2, "tmp_V_2_fu_142_p2");
    sc_trace(mVcdFile, tmp_V_2_reg_261, "tmp_V_2_reg_261");
    sc_trace(mVcdFile, mul_ln1118_fu_242_p2, "mul_ln1118_fu_242_p2");
    sc_trace(mVcdFile, mul_ln1118_reg_266, "mul_ln1118_reg_266");
    sc_trace(mVcdFile, icmp_ln8_fu_136_p2, "icmp_ln8_fu_136_p2");
    sc_trace(mVcdFile, j_fu_158_p2, "j_fu_158_p2");
    sc_trace(mVcdFile, j_reg_274, "j_reg_274");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln9_fu_152_p2, "icmp_ln9_fu_152_p2");
    sc_trace(mVcdFile, select_ln1496_fu_219_p3, "select_ln1496_fu_219_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, trunc_ln_reg_294, "trunc_ln_reg_294");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tmp_V_reg_80, "tmp_V_reg_80");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, r_V_reg_92, "r_V_reg_92");
    sc_trace(mVcdFile, t_V_2_reg_103, "t_V_2_reg_103");
    sc_trace(mVcdFile, j_0_reg_115, "j_0_reg_115");
    sc_trace(mVcdFile, zext_ln10_fu_164_p1, "zext_ln10_fu_164_p1");
    sc_trace(mVcdFile, zext_ln14_fu_237_p1, "zext_ln14_fu_237_p1");
    sc_trace(mVcdFile, t_V_fu_169_p3, "t_V_fu_169_p3");
    sc_trace(mVcdFile, grp_fu_181_p0, "grp_fu_181_p0");
    sc_trace(mVcdFile, grp_fu_181_p1, "grp_fu_181_p1");
    sc_trace(mVcdFile, shl_ln_fu_187_p3, "shl_ln_fu_187_p3");
    sc_trace(mVcdFile, icmp_ln1497_fu_200_p2, "icmp_ln1497_fu_200_p2");
    sc_trace(mVcdFile, count_V_fu_205_p2, "count_V_fu_205_p2");
    sc_trace(mVcdFile, icmp_ln1496_fu_195_p2, "icmp_ln1496_fu_195_p2");
    sc_trace(mVcdFile, select_ln10_fu_211_p3, "select_ln10_fu_211_p3");
    sc_trace(mVcdFile, grp_fu_181_p2, "grp_fu_181_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_242_p0, "mul_ln1118_fu_242_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_242_p1, "mul_ln1118_fu_242_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_181_p00, "grp_fu_181_p00");
    sc_trace(mVcdFile, mul_ln1118_fu_242_p00, "mul_ln1118_fu_242_p00");
#endif

    }
    mHdltvinHandle.open("estimate_FR.hdltvin.dat");
    mHdltvoutHandle.open("estimate_FR.hdltvout.dat");
}

estimate_FR::~estimate_FR() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete estimate_FR_mul_80ns_82ns_161_5_1_U1;
    delete estimate_FR_mul_mul_8ns_14ns_22_1_1_U2;
}

void estimate_FR::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void estimate_FR::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_136_p2.read(), ap_const_lv1_0))) {
        j_0_reg_115 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_0_reg_115 = j_reg_274.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        r_V_reg_92 = add_ln8_reg_253.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_V_reg_92 = ap_const_lv21_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_136_p2.read(), ap_const_lv1_0))) {
        t_V_2_reg_103 = ap_const_lv64_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        t_V_2_reg_103 = select_ln1496_fu_219_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_V_reg_80 = tmp_V_2_reg_261.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_V_reg_80 = ap_const_lv8_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        add_ln8_reg_253 = add_ln8_fu_130_p2.read();
        tmp_V_2_reg_261 = tmp_V_2_fu_142_p2.read();
        zext_ln8_reg_248 = zext_ln8_fu_126_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_274 = j_fu_158_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_136_p2.read(), ap_const_lv1_0))) {
        mul_ln1118_reg_266 = mul_ln1118_fu_242_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        trunc_ln_reg_294 = grp_fu_181_p2.read().range(100, 93);
    }
}

void estimate_FR::thread_FR_V_address0() {
    FR_V_address0 =  (sc_lv<8>) (zext_ln14_fu_237_p1.read());
}

void estimate_FR::thread_FR_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        FR_V_ce0 = ap_const_logic_1;
    } else {
        FR_V_ce0 = ap_const_logic_0;
    }
}

void estimate_FR::thread_FR_V_d0() {
    FR_V_d0 = trunc_ln_reg_294.read();
}

void estimate_FR::thread_FR_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        FR_V_we0 = ap_const_logic_1;
    } else {
        FR_V_we0 = ap_const_logic_0;
    }
}

void estimate_FR::thread_add_ln8_fu_130_p2() {
    add_ln8_fu_130_p2 = (!r_V_reg_92.read().is_01() || !ap_const_lv21_1999.is_01())? sc_lv<21>(): (sc_biguint<21>(r_V_reg_92.read()) + sc_biguint<21>(ap_const_lv21_1999));
}

void estimate_FR::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void estimate_FR::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void estimate_FR::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void estimate_FR::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void estimate_FR::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void estimate_FR::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void estimate_FR::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_136_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void estimate_FR::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void estimate_FR::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln8_fu_136_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void estimate_FR::thread_count_V_fu_205_p2() {
    count_V_fu_205_p2 = (!t_V_2_reg_103.read().is_01() || !ap_const_lv64_1.is_01())? sc_lv<64>(): (sc_biguint<64>(t_V_2_reg_103.read()) + sc_biguint<64>(ap_const_lv64_1));
}

void estimate_FR::thread_grp_fu_181_p0() {
    grp_fu_181_p0 =  (sc_lv<80>) (grp_fu_181_p00.read());
}

void estimate_FR::thread_grp_fu_181_p00() {
    grp_fu_181_p00 = esl_zext<161,80>(t_V_fu_169_p3.read());
}

void estimate_FR::thread_grp_fu_181_p1() {
    grp_fu_181_p1 =  (sc_lv<82>) (ap_const_lv161_lc_1);
}

void estimate_FR::thread_icmp_ln1496_fu_195_p2() {
    icmp_ln1496_fu_195_p2 = (!shl_ln_fu_187_p3.read().is_01() || !zext_ln8_reg_248.read().is_01())? sc_lv<1>(): (sc_biguint<22>(shl_ln_fu_187_p3.read()) < sc_biguint<22>(zext_ln8_reg_248.read()));
}

void estimate_FR::thread_icmp_ln1497_fu_200_p2() {
    icmp_ln1497_fu_200_p2 = (!shl_ln_fu_187_p3.read().is_01() || !mul_ln1118_reg_266.read().is_01())? sc_lv<1>(): (sc_biguint<22>(shl_ln_fu_187_p3.read()) > sc_biguint<22>(mul_ln1118_reg_266.read()));
}

void estimate_FR::thread_icmp_ln8_fu_136_p2() {
    icmp_ln8_fu_136_p2 = (!tmp_V_reg_80.read().is_01() || !ap_const_lv8_C8.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_reg_80.read() == ap_const_lv8_C8);
}

void estimate_FR::thread_icmp_ln9_fu_152_p2() {
    icmp_ln9_fu_152_p2 = (!j_0_reg_115.read().is_01() || !ap_const_lv7_4B.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_115.read() == ap_const_lv7_4B);
}

void estimate_FR::thread_j_fu_158_p2() {
    j_fu_158_p2 = (!j_0_reg_115.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_0_reg_115.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void estimate_FR::thread_mul_ln1118_fu_242_p0() {
    mul_ln1118_fu_242_p0 =  (sc_lv<8>) (mul_ln1118_fu_242_p00.read());
}

void estimate_FR::thread_mul_ln1118_fu_242_p00() {
    mul_ln1118_fu_242_p00 = esl_zext<22,8>(tmp_V_2_fu_142_p2.read());
}

void estimate_FR::thread_mul_ln1118_fu_242_p1() {
    mul_ln1118_fu_242_p1 =  (sc_lv<14>) (ap_const_lv22_1999);
}

void estimate_FR::thread_select_ln10_fu_211_p3() {
    select_ln10_fu_211_p3 = (!icmp_ln1497_fu_200_p2.read()[0].is_01())? sc_lv<64>(): ((icmp_ln1497_fu_200_p2.read()[0].to_bool())? t_V_2_reg_103.read(): count_V_fu_205_p2.read());
}

void estimate_FR::thread_select_ln1496_fu_219_p3() {
    select_ln1496_fu_219_p3 = (!icmp_ln1496_fu_195_p2.read()[0].is_01())? sc_lv<64>(): ((icmp_ln1496_fu_195_p2.read()[0].to_bool())? t_V_2_reg_103.read(): select_ln10_fu_211_p3.read());
}

void estimate_FR::thread_shl_ln_fu_187_p3() {
    shl_ln_fu_187_p3 = esl_concat<12,10>(spksTime_V_q0.read(), ap_const_lv10_0);
}

void estimate_FR::thread_spksTime_V_address0() {
    spksTime_V_address0 =  (sc_lv<7>) (zext_ln10_fu_164_p1.read());
}

void estimate_FR::thread_spksTime_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        spksTime_V_ce0 = ap_const_logic_1;
    } else {
        spksTime_V_ce0 = ap_const_logic_0;
    }
}

void estimate_FR::thread_t_V_fu_169_p3() {
    t_V_fu_169_p3 = esl_concat<64,16>(t_V_2_reg_103.read(), ap_const_lv16_0);
}

void estimate_FR::thread_tmp_V_2_fu_142_p2() {
    tmp_V_2_fu_142_p2 = (!tmp_V_reg_80.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_V_reg_80.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void estimate_FR::thread_zext_ln10_fu_164_p1() {
    zext_ln10_fu_164_p1 = esl_zext<64,7>(j_0_reg_115.read());
}

void estimate_FR::thread_zext_ln14_fu_237_p1() {
    zext_ln14_fu_237_p1 = esl_zext<64,8>(tmp_V_reg_80.read());
}

void estimate_FR::thread_zext_ln8_fu_126_p1() {
    zext_ln8_fu_126_p1 = esl_zext<22,21>(r_V_reg_92.read());
}

void estimate_FR::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln8_fu_136_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln9_fu_152_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXX";
            break;
    }
}

void estimate_FR::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"spksTime_V_address0\" :  \"" << spksTime_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"spksTime_V_ce0\" :  \"" << spksTime_V_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"spksTime_V_q0\" :  \"" << spksTime_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"FR_V_address0\" :  \"" << FR_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"FR_V_ce0\" :  \"" << FR_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"FR_V_we0\" :  \"" << FR_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"FR_V_d0\" :  \"" << FR_V_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

