// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _estimate_ISI_encode_HH_
#define _estimate_ISI_encode_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "estimate_ISI_encode_ISIquan_V.h"
#include "estimate_ISI_encode_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 11,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct estimate_ISI_encode : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    estimate_ISI_encode(sc_module_name name);
    SC_HAS_PROCESS(estimate_ISI_encode);

    ~estimate_ISI_encode();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    estimate_ISI_encode_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* estimate_ISI_encode_AXILiteS_s_axi_U;
    estimate_ISI_encode_ISIquan_V* ISIquan_V_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<10> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<7> > inputs_address0;
    sc_signal< sc_logic > inputs_ce0;
    sc_signal< sc_lv<32> > inputs_q0;
    sc_signal< sc_lv<7> > rem_r_address0;
    sc_signal< sc_logic > rem_r_ce0;
    sc_signal< sc_logic > rem_r_we0;
    sc_signal< sc_lv<32> > rem_r_d0;
    sc_signal< sc_lv<32> > rem_r_q0;
    sc_signal< sc_lv<4> > output_r_address0;
    sc_signal< sc_logic > output_r_ce0;
    sc_signal< sc_logic > output_r_we0;
    sc_signal< sc_lv<32> > output_r_d0;
    sc_signal< sc_lv<7> > j_fu_296_p2;
    sc_signal< sc_lv<7> > j_reg_650;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > zext_ln18_fu_302_p1;
    sc_signal< sc_lv<64> > zext_ln18_reg_655;
    sc_signal< sc_lv<1> > icmp_ln17_fu_290_p2;
    sc_signal< sc_lv<1> > trunc_ln301_fu_307_p1;
    sc_signal< sc_lv<1> > trunc_ln301_reg_667;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_3_fu_311_p3;
    sc_signal< sc_lv<1> > tmp_3_reg_671;
    sc_signal< sc_lv<7> > rem_addr_reg_675;
    sc_signal< sc_lv<19> > tmp_1_reg_680;
    sc_signal< sc_lv<11> > tmp_2_reg_685;
    sc_signal< sc_lv<12> > sub_ln214_fu_360_p2;
    sc_signal< sc_lv<12> > sub_ln214_reg_690;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<7> > ret_V_fu_394_p2;
    sc_signal< sc_lv<7> > ret_V_reg_695;
    sc_signal< sc_lv<6> > trunc_ln2_reg_700;
    sc_signal< sc_lv<12> > sub_ln214_1_fu_450_p2;
    sc_signal< sc_lv<12> > sub_ln214_1_reg_705;
    sc_signal< sc_lv<4> > i_fu_537_p2;
    sc_signal< sc_lv<4> > i_reg_713;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<7> > shl_ln_fu_543_p3;
    sc_signal< sc_lv<7> > shl_ln_reg_718;
    sc_signal< sc_lv<1> > icmp_ln43_fu_531_p2;
    sc_signal< sc_lv<4> > ISIquan_V_q0;
    sc_signal< sc_lv<4> > ISIquan_V_load_reg_738;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<4> > ISIquan_V_q1;
    sc_signal< sc_lv<4> > ISIquan_V_load_1_reg_743;
    sc_signal< sc_lv<4> > ISIquan_V_load_2_reg_758;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<4> > ISIquan_V_load_3_reg_763;
    sc_signal< sc_lv<4> > ISIquan_V_load_4_reg_778;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<4> > ISIquan_V_load_5_reg_783;
    sc_signal< sc_lv<7> > ISIquan_V_address0;
    sc_signal< sc_logic > ISIquan_V_ce0;
    sc_signal< sc_logic > ISIquan_V_we0;
    sc_signal< sc_lv<4> > ISIquan_V_d0;
    sc_signal< sc_lv<7> > ISIquan_V_address1;
    sc_signal< sc_logic > ISIquan_V_ce1;
    sc_signal< sc_lv<7> > j_0_reg_267;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > i_0_reg_278;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<7> > ISIquan_V_addr_9_gep_fu_187_p3;
    sc_signal< sc_lv<64> > zext_ln44_fu_551_p1;
    sc_signal< sc_lv<64> > zext_ln45_fu_562_p1;
    sc_signal< sc_lv<64> > zext_ln46_fu_572_p1;
    sc_signal< sc_lv<64> > zext_ln47_fu_582_p1;
    sc_signal< sc_lv<64> > zext_ln48_fu_592_p1;
    sc_signal< sc_lv<64> > zext_ln49_fu_602_p1;
    sc_signal< sc_lv<64> > zext_ln50_fu_612_p1;
    sc_signal< sc_lv<64> > zext_ln51_fu_622_p1;
    sc_signal< sc_lv<64> > zext_ln52_fu_642_p1;
    sc_signal< sc_lv<4> > ISI_q_V_fu_512_p3;
    sc_signal< sc_lv<12> > and_ln_fu_349_p3;
    sc_signal< sc_lv<12> > trunc_ln214_fu_356_p1;
    sc_signal< sc_lv<6> > ISIPre_n_V_fu_376_p4;
    sc_signal< sc_lv<6> > ISI_n_V_fu_366_p4;
    sc_signal< sc_lv<7> > lhs_V_fu_386_p1;
    sc_signal< sc_lv<7> > rhs_V_fu_390_p1;
    sc_signal< sc_lv<6> > ret_V_1_fu_400_p0;
    sc_signal< sc_lv<6> > ret_V_1_fu_400_p1;
    sc_signal< sc_lv<7> > ret_V_1_fu_400_p2;
    sc_signal< sc_lv<7> > trunc_ln3_fu_416_p4;
    sc_signal< sc_lv<7> > r_V_1_fu_430_p4;
    sc_signal< sc_lv<12> > ISIPre_V_fu_339_p4;
    sc_signal< sc_lv<12> > r_V_2_fu_440_p1;
    sc_signal< sc_lv<12> > sub_ln1354_fu_444_p2;
    sc_signal< sc_lv<12> > r_V_fu_426_p1;
    sc_signal< sc_lv<7> > zext_ln891_fu_456_p1;
    sc_signal< sc_lv<1> > icmp_ln891_fu_459_p2;
    sc_signal< sc_lv<12> > select_ln891_fu_464_p3;
    sc_signal< sc_lv<1> > icmp_ln887_fu_470_p2;
    sc_signal< sc_lv<1> > icmp_ln899_fu_476_p2;
    sc_signal< sc_lv<1> > xor_ln887_fu_492_p2;
    sc_signal< sc_lv<1> > and_ln899_fu_498_p2;
    sc_signal< sc_lv<4> > trunc_ln1503_3_fu_482_p4;
    sc_signal< sc_lv<4> > select_ln899_fu_504_p3;
    sc_signal< sc_lv<7> > or_ln45_fu_556_p2;
    sc_signal< sc_lv<7> > or_ln46_fu_567_p2;
    sc_signal< sc_lv<7> > or_ln47_fu_577_p2;
    sc_signal< sc_lv<7> > or_ln48_fu_587_p2;
    sc_signal< sc_lv<7> > or_ln49_fu_597_p2;
    sc_signal< sc_lv<7> > or_ln50_fu_607_p2;
    sc_signal< sc_lv<7> > or_ln51_fu_617_p2;
    sc_signal< sc_lv<10> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<10> ap_ST_fsm_state1;
    static const sc_lv<10> ap_ST_fsm_state2;
    static const sc_lv<10> ap_ST_fsm_state3;
    static const sc_lv<10> ap_ST_fsm_state4;
    static const sc_lv<10> ap_ST_fsm_state5;
    static const sc_lv<10> ap_ST_fsm_state6;
    static const sc_lv<10> ap_ST_fsm_state7;
    static const sc_lv<10> ap_ST_fsm_state8;
    static const sc_lv<10> ap_ST_fsm_state9;
    static const sc_lv<10> ap_ST_fsm_state10;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<7> ap_const_lv7_60;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_18;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<12> ap_const_lv12_A;
    static const sc_lv<12> ap_const_lv12_65;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<7> ap_const_lv7_2;
    static const sc_lv<7> ap_const_lv7_3;
    static const sc_lv<7> ap_const_lv7_4;
    static const sc_lv<7> ap_const_lv7_5;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_7;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ISIPre_V_fu_339_p4();
    void thread_ISIPre_n_V_fu_376_p4();
    void thread_ISI_n_V_fu_366_p4();
    void thread_ISI_q_V_fu_512_p3();
    void thread_ISIquan_V_addr_9_gep_fu_187_p3();
    void thread_ISIquan_V_address0();
    void thread_ISIquan_V_address1();
    void thread_ISIquan_V_ce0();
    void thread_ISIquan_V_ce1();
    void thread_ISIquan_V_d0();
    void thread_ISIquan_V_we0();
    void thread_and_ln899_fu_498_p2();
    void thread_and_ln_fu_349_p3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_i_fu_537_p2();
    void thread_icmp_ln17_fu_290_p2();
    void thread_icmp_ln43_fu_531_p2();
    void thread_icmp_ln887_fu_470_p2();
    void thread_icmp_ln891_fu_459_p2();
    void thread_icmp_ln899_fu_476_p2();
    void thread_inputs_address0();
    void thread_inputs_ce0();
    void thread_j_fu_296_p2();
    void thread_lhs_V_fu_386_p1();
    void thread_or_ln45_fu_556_p2();
    void thread_or_ln46_fu_567_p2();
    void thread_or_ln47_fu_577_p2();
    void thread_or_ln48_fu_587_p2();
    void thread_or_ln49_fu_597_p2();
    void thread_or_ln50_fu_607_p2();
    void thread_or_ln51_fu_617_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_r_V_1_fu_430_p4();
    void thread_r_V_2_fu_440_p1();
    void thread_r_V_fu_426_p1();
    void thread_rem_r_address0();
    void thread_rem_r_ce0();
    void thread_rem_r_d0();
    void thread_rem_r_we0();
    void thread_ret_V_1_fu_400_p0();
    void thread_ret_V_1_fu_400_p1();
    void thread_ret_V_1_fu_400_p2();
    void thread_ret_V_fu_394_p2();
    void thread_rhs_V_fu_390_p1();
    void thread_select_ln891_fu_464_p3();
    void thread_select_ln899_fu_504_p3();
    void thread_shl_ln_fu_543_p3();
    void thread_sub_ln1354_fu_444_p2();
    void thread_sub_ln214_1_fu_450_p2();
    void thread_sub_ln214_fu_360_p2();
    void thread_tmp_3_fu_311_p3();
    void thread_trunc_ln1503_3_fu_482_p4();
    void thread_trunc_ln214_fu_356_p1();
    void thread_trunc_ln301_fu_307_p1();
    void thread_trunc_ln3_fu_416_p4();
    void thread_xor_ln887_fu_492_p2();
    void thread_zext_ln18_fu_302_p1();
    void thread_zext_ln44_fu_551_p1();
    void thread_zext_ln45_fu_562_p1();
    void thread_zext_ln46_fu_572_p1();
    void thread_zext_ln47_fu_582_p1();
    void thread_zext_ln48_fu_592_p1();
    void thread_zext_ln49_fu_602_p1();
    void thread_zext_ln50_fu_612_p1();
    void thread_zext_ln51_fu_622_p1();
    void thread_zext_ln52_fu_642_p1();
    void thread_zext_ln891_fu_456_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
