// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _estimate_FR_HH_
#define _estimate_FR_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "estimate_FR_dadddsub_64ns_64ns_64_5_full_dsp_1.h"
#include "estimate_FR_dmul_64ns_64ns_64_6_max_dsp_1.h"
#include "estimate_FR_ddiv_64ns_64ns_64_31_1.h"
#include "estimate_FR_dcmp_64ns_64ns_1_2_1.h"
#include "estimate_FR_ISI.h"

namespace ap_rtl {

struct estimate_FR : public sc_module {
    // Port declarations 21
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<7> > spksTime_address0;
    sc_out< sc_logic > spksTime_ce0;
    sc_in< sc_lv<64> > spksTime_q0;
    sc_out< sc_lv<7> > spksTime_address1;
    sc_out< sc_logic > spksTime_ce1;
    sc_in< sc_lv<64> > spksTime_q1;
    sc_out< sc_lv<7> > FR_address0;
    sc_out< sc_logic > FR_ce0;
    sc_out< sc_logic > FR_we0;
    sc_out< sc_lv<64> > FR_d0;
    sc_out< sc_lv<7> > FR_address1;
    sc_out< sc_logic > FR_ce1;
    sc_out< sc_logic > FR_we1;
    sc_out< sc_lv<64> > FR_d1;
    sc_in< sc_lv<64> > FR_q1;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;
    sc_signal< sc_lv<64> > ap_var_for_const2;
    sc_signal< sc_lv<64> > ap_var_for_const3;
    sc_signal< sc_lv<64> > ap_var_for_const4;
    sc_signal< sc_lv<5> > ap_var_for_const5;


    // Module declarations
    estimate_FR(sc_module_name name);
    SC_HAS_PROCESS(estimate_FR);

    ~estimate_FR();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    estimate_FR_ISI* ISI_U;
    estimate_FR_dadddsub_64ns_64ns_64_5_full_dsp_1<1,5,64,64,64>* estimate_FR_dadddsub_64ns_64ns_64_5_full_dsp_1_U1;
    estimate_FR_dmul_64ns_64ns_64_6_max_dsp_1<1,6,64,64,64>* estimate_FR_dmul_64ns_64ns_64_6_max_dsp_1_U2;
    estimate_FR_dmul_64ns_64ns_64_6_max_dsp_1<1,6,64,64,64>* estimate_FR_dmul_64ns_64ns_64_6_max_dsp_1_U3;
    estimate_FR_ddiv_64ns_64ns_64_31_1<1,31,64,64,64>* estimate_FR_ddiv_64ns_64ns_64_31_1_U4;
    estimate_FR_dcmp_64ns_64ns_1_2_1<1,2,64,64,1>* estimate_FR_dcmp_64ns_64ns_1_2_1_U5;
    sc_signal< sc_lv<62> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > grp_fu_180_p2;
    sc_signal< sc_lv<64> > reg_205;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state47;
    sc_signal< sc_lv<7> > i_fu_217_p2;
    sc_signal< sc_lv<7> > i_reg_305;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln10_fu_211_p2;
    sc_signal< sc_lv<64> > zext_ln11_1_fu_228_p1;
    sc_signal< sc_lv<64> > zext_ln11_1_reg_315;
    sc_signal< sc_lv<64> > spksTime_load_reg_325;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > spksTime_load_1_reg_330;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > icmp_ln13_fu_233_p2;
    sc_signal< sc_lv<7> > FR_addr_1_reg_343;
    sc_signal< sc_lv<64> > ISI_q0;
    sc_signal< sc_lv<64> > ISI_load_reg_349;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<64> > grp_fu_195_p2;
    sc_signal< sc_lv<64> > tmp_1_reg_354;
    sc_signal< sc_logic > ap_CS_fsm_state42;
    sc_signal< sc_lv<1> > icmp_ln15_fu_263_p2;
    sc_signal< sc_lv<1> > icmp_ln15_reg_362;
    sc_signal< sc_logic > ap_CS_fsm_state48;
    sc_signal< sc_lv<1> > icmp_ln15_1_fu_269_p2;
    sc_signal< sc_lv<1> > icmp_ln15_1_reg_367;
    sc_signal< sc_logic > ap_CS_fsm_state49;
    sc_signal< sc_lv<1> > and_ln15_fu_290_p2;
    sc_signal< sc_lv<1> > and_ln15_reg_377;
    sc_signal< sc_lv<64> > FR_load_reg_381;
    sc_signal< sc_logic > ap_CS_fsm_state50;
    sc_signal< sc_lv<64> > grp_fu_185_p2;
    sc_signal< sc_lv<64> > tmp_4_reg_386;
    sc_signal< sc_logic > ap_CS_fsm_state56;
    sc_signal< sc_lv<64> > grp_fu_190_p2;
    sc_signal< sc_lv<64> > tmp_5_reg_391;
    sc_signal< sc_lv<64> > tmp_6_reg_396;
    sc_signal< sc_logic > ap_CS_fsm_state61;
    sc_signal< sc_lv<7> > j_fu_296_p2;
    sc_signal< sc_logic > ap_CS_fsm_state62;
    sc_signal< sc_lv<7> > ISI_address0;
    sc_signal< sc_logic > ISI_ce0;
    sc_signal< sc_logic > ISI_we0;
    sc_signal< sc_lv<7> > i_0_reg_134;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<64> > ap_phi_mux_empty_7_phi_fu_173_p4;
    sc_signal< sc_lv<64> > empty_5_reg_145;
    sc_signal< sc_lv<7> > j_0_reg_157;
    sc_signal< sc_lv<64> > empty_7_reg_169;
    sc_signal< sc_lv<64> > zext_ln11_fu_223_p1;
    sc_signal< sc_lv<64> > zext_ln14_fu_239_p1;
    sc_signal< sc_lv<64> > zext_ln15_fu_281_p1;
    sc_signal< sc_lv<64> > grp_fu_180_p0;
    sc_signal< sc_lv<64> > grp_fu_180_p1;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state43;
    sc_signal< sc_logic > ap_CS_fsm_state57;
    sc_signal< sc_logic > ap_CS_fsm_state51;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > bitcast_ln15_fu_245_p1;
    sc_signal< sc_lv<11> > tmp_3_fu_249_p4;
    sc_signal< sc_lv<52> > trunc_ln15_fu_259_p1;
    sc_signal< sc_lv<7> > add_ln15_fu_275_p2;
    sc_signal< sc_lv<1> > or_ln15_fu_286_p2;
    sc_signal< sc_lv<1> > grp_fu_200_p2;
    sc_signal< sc_lv<2> > grp_fu_180_opcode;
    sc_signal< sc_lv<62> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<62> ap_ST_fsm_state1;
    static const sc_lv<62> ap_ST_fsm_state2;
    static const sc_lv<62> ap_ST_fsm_state3;
    static const sc_lv<62> ap_ST_fsm_state4;
    static const sc_lv<62> ap_ST_fsm_state5;
    static const sc_lv<62> ap_ST_fsm_state6;
    static const sc_lv<62> ap_ST_fsm_state7;
    static const sc_lv<62> ap_ST_fsm_state8;
    static const sc_lv<62> ap_ST_fsm_state9;
    static const sc_lv<62> ap_ST_fsm_state10;
    static const sc_lv<62> ap_ST_fsm_state11;
    static const sc_lv<62> ap_ST_fsm_state12;
    static const sc_lv<62> ap_ST_fsm_state13;
    static const sc_lv<62> ap_ST_fsm_state14;
    static const sc_lv<62> ap_ST_fsm_state15;
    static const sc_lv<62> ap_ST_fsm_state16;
    static const sc_lv<62> ap_ST_fsm_state17;
    static const sc_lv<62> ap_ST_fsm_state18;
    static const sc_lv<62> ap_ST_fsm_state19;
    static const sc_lv<62> ap_ST_fsm_state20;
    static const sc_lv<62> ap_ST_fsm_state21;
    static const sc_lv<62> ap_ST_fsm_state22;
    static const sc_lv<62> ap_ST_fsm_state23;
    static const sc_lv<62> ap_ST_fsm_state24;
    static const sc_lv<62> ap_ST_fsm_state25;
    static const sc_lv<62> ap_ST_fsm_state26;
    static const sc_lv<62> ap_ST_fsm_state27;
    static const sc_lv<62> ap_ST_fsm_state28;
    static const sc_lv<62> ap_ST_fsm_state29;
    static const sc_lv<62> ap_ST_fsm_state30;
    static const sc_lv<62> ap_ST_fsm_state31;
    static const sc_lv<62> ap_ST_fsm_state32;
    static const sc_lv<62> ap_ST_fsm_state33;
    static const sc_lv<62> ap_ST_fsm_state34;
    static const sc_lv<62> ap_ST_fsm_state35;
    static const sc_lv<62> ap_ST_fsm_state36;
    static const sc_lv<62> ap_ST_fsm_state37;
    static const sc_lv<62> ap_ST_fsm_state38;
    static const sc_lv<62> ap_ST_fsm_state39;
    static const sc_lv<62> ap_ST_fsm_state40;
    static const sc_lv<62> ap_ST_fsm_state41;
    static const sc_lv<62> ap_ST_fsm_state42;
    static const sc_lv<62> ap_ST_fsm_state43;
    static const sc_lv<62> ap_ST_fsm_state44;
    static const sc_lv<62> ap_ST_fsm_state45;
    static const sc_lv<62> ap_ST_fsm_state46;
    static const sc_lv<62> ap_ST_fsm_state47;
    static const sc_lv<62> ap_ST_fsm_state48;
    static const sc_lv<62> ap_ST_fsm_state49;
    static const sc_lv<62> ap_ST_fsm_state50;
    static const sc_lv<62> ap_ST_fsm_state51;
    static const sc_lv<62> ap_ST_fsm_state52;
    static const sc_lv<62> ap_ST_fsm_state53;
    static const sc_lv<62> ap_ST_fsm_state54;
    static const sc_lv<62> ap_ST_fsm_state55;
    static const sc_lv<62> ap_ST_fsm_state56;
    static const sc_lv<62> ap_ST_fsm_state57;
    static const sc_lv<62> ap_ST_fsm_state58;
    static const sc_lv<62> ap_ST_fsm_state59;
    static const sc_lv<62> ap_ST_fsm_state60;
    static const sc_lv<62> ap_ST_fsm_state61;
    static const sc_lv<62> ap_ST_fsm_state62;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_2E;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_29;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_31;
    static const sc_lv<32> ap_const_lv32_37;
    static const sc_lv<32> ap_const_lv32_3C;
    static const sc_lv<32> ap_const_lv32_3D;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_2A;
    static const sc_lv<32> ap_const_lv32_38;
    static const sc_lv<64> ap_const_lv64_3FA0000000000000;
    static const sc_lv<32> ap_const_lv32_32;
    static const sc_lv<64> ap_const_lv64_3FEF000000000000;
    static const sc_lv<64> ap_const_lv64_3FF0000000000000;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<64> ap_const_lv64_403E000000000000;
    static const sc_lv<7> ap_const_lv7_4A;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<11> ap_const_lv11_7FF;
    static const sc_lv<52> ap_const_lv52_0;
    static const sc_lv<7> ap_const_lv7_7F;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const4();
    void thread_ap_var_for_const5();
    void thread_ap_clk_no_reset_();
    void thread_FR_address0();
    void thread_FR_address1();
    void thread_FR_ce0();
    void thread_FR_ce1();
    void thread_FR_d0();
    void thread_FR_d1();
    void thread_FR_we0();
    void thread_FR_we1();
    void thread_ISI_address0();
    void thread_ISI_ce0();
    void thread_ISI_we0();
    void thread_add_ln15_fu_275_p2();
    void thread_and_ln15_fu_290_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state42();
    void thread_ap_CS_fsm_state43();
    void thread_ap_CS_fsm_state47();
    void thread_ap_CS_fsm_state48();
    void thread_ap_CS_fsm_state49();
    void thread_ap_CS_fsm_state50();
    void thread_ap_CS_fsm_state51();
    void thread_ap_CS_fsm_state56();
    void thread_ap_CS_fsm_state57();
    void thread_ap_CS_fsm_state61();
    void thread_ap_CS_fsm_state62();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_phi_mux_empty_7_phi_fu_173_p4();
    void thread_ap_ready();
    void thread_bitcast_ln15_fu_245_p1();
    void thread_grp_fu_180_opcode();
    void thread_grp_fu_180_p0();
    void thread_grp_fu_180_p1();
    void thread_i_fu_217_p2();
    void thread_icmp_ln10_fu_211_p2();
    void thread_icmp_ln13_fu_233_p2();
    void thread_icmp_ln15_1_fu_269_p2();
    void thread_icmp_ln15_fu_263_p2();
    void thread_j_fu_296_p2();
    void thread_or_ln15_fu_286_p2();
    void thread_spksTime_address0();
    void thread_spksTime_address1();
    void thread_spksTime_ce0();
    void thread_spksTime_ce1();
    void thread_tmp_3_fu_249_p4();
    void thread_trunc_ln15_fu_259_p1();
    void thread_zext_ln11_1_fu_228_p1();
    void thread_zext_ln11_fu_223_p1();
    void thread_zext_ln14_fu_239_p1();
    void thread_zext_ln15_fu_281_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
