// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="estimate_FR_2,hls_ip_2019_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.657000,HLS_SYN_LAT=222,HLS_SYN_TPT=none,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=707,HLS_SYN_LUT=1576,HLS_VERSION=2019_1}" *)

module estimate_FR_2 (
        ap_clk,
        ap_rst_n,
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 12'd1;
parameter    ap_ST_fsm_pp0_stage0 = 12'd2;
parameter    ap_ST_fsm_pp0_stage1 = 12'd4;
parameter    ap_ST_fsm_state5 = 12'd8;
parameter    ap_ST_fsm_pp1_stage0 = 12'd16;
parameter    ap_ST_fsm_pp1_stage1 = 12'd32;
parameter    ap_ST_fsm_pp1_stage2 = 12'd64;
parameter    ap_ST_fsm_pp1_stage3 = 12'd128;
parameter    ap_ST_fsm_state11 = 12'd256;
parameter    ap_ST_fsm_pp2_stage0 = 12'd512;
parameter    ap_ST_fsm_pp2_stage1 = 12'd1024;
parameter    ap_ST_fsm_state15 = 12'd2048;
parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 10;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [11:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [5:0] inputs_0_address0;
reg    inputs_0_ce0;
wire   [31:0] inputs_0_q0;
wire   [5:0] inputs_1_address0;
reg    inputs_1_ce0;
wire   [31:0] inputs_1_q0;
reg   [3:0] counts_0_address0;
reg    counts_0_ce0;
reg    counts_0_we0;
reg   [31:0] counts_0_d0;
wire   [31:0] counts_0_q0;
reg   [3:0] counts_1_address0;
reg    counts_1_ce0;
reg    counts_1_we0;
reg   [31:0] counts_1_d0;
wire   [31:0] counts_1_q0;
reg   [3:0] outputs_0_address0;
reg    outputs_0_ce0;
reg    outputs_0_we0;
reg   [31:0] outputs_0_d0;
reg   [3:0] outputs_1_address0;
reg    outputs_1_ce0;
reg    outputs_1_we0;
reg   [31:0] outputs_1_d0;
reg   [4:0] j_0_0_reg_822;
reg   [0:0] p_090_0217_0_reg_834;
reg   [6:0] i_0_0_reg_846;
reg   [4:0] k_0_0_reg_858;
wire   [0:0] icmp_ln12_fu_956_p2;
reg   [0:0] icmp_ln12_reg_1638;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] or_ln12_fu_1010_p2;
reg   [4:0] or_ln12_reg_1652;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
wire   [4:0] or_ln12_1_fu_1031_p2;
reg   [4:0] or_ln12_1_reg_1662;
wire   [4:0] add_ln12_fu_1052_p2;
reg   [4:0] add_ln12_reg_1672;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] icmp_ln19_fu_1082_p2;
reg   [0:0] icmp_ln19_reg_1677;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state6_pp1_stage0_iter0;
wire    ap_block_state10_pp1_stage0_iter1;
wire    ap_block_pp1_stage0_11001;
wire   [0:0] trunc_ln301_11_fu_1104_p1;
reg   [0:0] trunc_ln301_11_reg_1691;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_state7_pp1_stage1_iter0;
wire    ap_block_pp1_stage1_11001;
reg   [0:0] tmp_10_reg_1695;
reg   [4:0] cnt_0_V_addr_5_reg_1699;
reg   [4:0] cnt_2_V_addr_5_reg_1705;
wire   [0:0] trunc_ln301_12_fu_1122_p1;
reg   [0:0] trunc_ln301_12_reg_1711;
reg   [0:0] tmp_11_reg_1715;
reg    ap_enable_reg_pp1_iter0;
reg   [4:0] cnt_1_V_addr_8_reg_1720;
reg   [4:0] cnt_3_V_addr_8_reg_1726;
wire   [0:0] icmp_ln1503_1_fu_1204_p2;
reg   [0:0] icmp_ln1503_1_reg_1738;
wire    ap_CS_fsm_pp1_stage2;
wire    ap_block_state8_pp1_stage2_iter0;
wire    ap_block_pp1_stage2_11001;
reg   [4:0] cnt_0_V_addr_9_reg_1743;
wire    ap_CS_fsm_pp1_stage3;
wire    ap_block_state9_pp1_stage3_iter0;
wire    ap_block_pp1_stage3_11001;
reg   [4:0] cnt_2_V_addr_9_reg_1749;
wire   [0:0] icmp_ln1503_fu_1222_p2;
reg   [0:0] icmp_ln1503_reg_1755;
reg   [4:0] FR_0_V_addr_2_reg_1760;
reg   [4:0] FR_2_V_addr_2_reg_1765;
reg   [4:0] cnt_1_V_addr_9_reg_1770;
reg   [4:0] cnt_3_V_addr_9_reg_1776;
reg   [4:0] FR_1_V_addr_4_reg_1782;
reg   [4:0] FR_3_V_addr_4_reg_1787;
wire   [6:0] add_ln19_fu_1236_p2;
reg   [6:0] add_ln19_reg_1792;
wire   [0:0] icmp_ln31_fu_1300_p2;
reg   [0:0] icmp_ln31_reg_1797;
wire    ap_CS_fsm_pp2_stage0;
wire    ap_block_state12_pp2_stage0_iter0;
wire    ap_block_state14_pp2_stage0_iter1;
wire    ap_block_pp2_stage0_11001;
wire    ap_CS_fsm_pp2_stage1;
wire    ap_block_state13_pp2_stage1_iter0;
wire    ap_block_pp2_stage1_11001;
reg   [3:0] lshr_ln36_1_reg_1901;
reg   [3:0] lshr_ln36_2_reg_1946;
wire   [4:0] add_ln31_fu_1516_p2;
reg   [4:0] add_ln31_reg_1971;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_CS_fsm_state5;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state6;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage3_subdone;
wire    ap_CS_fsm_state11;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state12;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_pp2_stage1_subdone;
reg   [4:0] cnt_0_V_address0;
reg    cnt_0_V_ce0;
reg    cnt_0_V_we0;
reg   [5:0] cnt_0_V_d0;
wire   [5:0] cnt_0_V_q0;
reg   [4:0] cnt_0_V_address1;
reg    cnt_0_V_ce1;
reg    cnt_0_V_we1;
reg   [5:0] cnt_0_V_d1;
wire   [5:0] cnt_0_V_q1;
reg   [4:0] cnt_1_V_address0;
reg    cnt_1_V_ce0;
reg    cnt_1_V_we0;
reg   [5:0] cnt_1_V_d0;
wire   [5:0] cnt_1_V_q0;
reg   [4:0] cnt_1_V_address1;
reg    cnt_1_V_ce1;
reg    cnt_1_V_we1;
wire   [5:0] cnt_1_V_d1;
wire   [5:0] cnt_1_V_q1;
reg   [4:0] cnt_2_V_address0;
reg    cnt_2_V_ce0;
reg    cnt_2_V_we0;
reg   [5:0] cnt_2_V_d0;
wire   [5:0] cnt_2_V_q0;
reg   [4:0] cnt_2_V_address1;
reg    cnt_2_V_ce1;
reg    cnt_2_V_we1;
wire   [5:0] cnt_2_V_d1;
wire   [5:0] cnt_2_V_q1;
reg   [4:0] cnt_3_V_address0;
reg    cnt_3_V_ce0;
reg    cnt_3_V_we0;
reg   [5:0] cnt_3_V_d0;
wire   [5:0] cnt_3_V_q0;
reg   [4:0] cnt_3_V_address1;
reg    cnt_3_V_ce1;
reg    cnt_3_V_we1;
wire   [5:0] cnt_3_V_d1;
wire   [5:0] cnt_3_V_q1;
reg   [4:0] FR_0_V_address0;
reg    FR_0_V_ce0;
reg    FR_0_V_we0;
wire   [6:0] FR_0_V_q0;
reg   [4:0] FR_0_V_address1;
reg    FR_0_V_ce1;
wire   [6:0] FR_0_V_q1;
reg   [4:0] FR_1_V_address0;
reg    FR_1_V_ce0;
reg    FR_1_V_we0;
wire   [6:0] FR_1_V_q0;
reg   [4:0] FR_1_V_address1;
reg    FR_1_V_ce1;
wire   [6:0] FR_1_V_q1;
reg   [4:0] FR_2_V_address0;
reg    FR_2_V_ce0;
reg    FR_2_V_we0;
wire   [6:0] FR_2_V_q0;
reg   [4:0] FR_2_V_address1;
reg    FR_2_V_ce1;
wire   [6:0] FR_2_V_q1;
reg   [4:0] FR_3_V_address0;
reg    FR_3_V_ce0;
reg    FR_3_V_we0;
wire   [6:0] FR_3_V_q0;
reg   [4:0] FR_3_V_address1;
reg    FR_3_V_ce1;
wire   [6:0] FR_3_V_q1;
reg   [4:0] ap_phi_mux_j_0_0_phi_fu_826_p4;
wire    ap_block_pp0_stage0;
wire    ap_block_pp1_stage0;
reg   [6:0] ap_phi_mux_i_0_0_phi_fu_850_p4;
reg   [4:0] ap_phi_mux_k_0_0_phi_fu_862_p4;
wire    ap_block_pp2_stage0;
wire   [63:0] zext_ln13_fu_972_p1;
wire   [63:0] zext_ln321_fu_983_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln321_1_fu_1002_p1;
wire   [63:0] zext_ln13_1_fu_1026_p1;
wire   [63:0] zext_ln13_2_fu_1047_p1;
wire   [63:0] zext_ln321_2_fu_1063_p1;
wire   [63:0] zext_ln321_3_fu_1075_p1;
wire   [63:0] zext_ln20_fu_1098_p1;
wire   [63:0] zext_ln738_fu_1116_p1;
wire    ap_block_pp1_stage1;
wire   [63:0] zext_ln738_1_fu_1134_p1;
wire   [63:0] zext_ln1503_fu_1214_p1;
wire    ap_block_pp1_stage3;
wire   [63:0] zext_ln1503_1_fu_1228_p1;
wire   [63:0] zext_ln555_fu_1306_p1;
wire   [63:0] zext_ln555_1_fu_1324_p1;
wire   [63:0] zext_ln36_1_fu_1369_p1;
wire    ap_block_pp2_stage1;
wire   [3:0] outputs_0_addr_gep_fu_624_p3;
wire   [3:0] outputs_1_addr_gep_fu_654_p3;
wire   [63:0] zext_ln555_2_fu_1466_p1;
wire   [63:0] zext_ln555_3_fu_1494_p1;
wire   [63:0] zext_ln36_4_fu_1545_p1;
wire   [3:0] outputs_0_addr_2_gep_fu_790_p3;
wire   [63:0] zext_ln36_6_fu_1603_p1;
wire   [3:0] outputs_1_addr_2_gep_fu_814_p3;
wire   [31:0] zext_ln36_fu_1354_p1;
wire   [31:0] zext_ln36_3_fu_1540_p1;
wire   [31:0] zext_ln36_2_fu_1426_p1;
wire   [31:0] zext_ln36_5_fu_1598_p1;
wire   [5:0] trunc_ln301_fu_978_p1;
wire   [5:0] trunc_ln301_3_fu_991_p1;
wire   [5:0] trunc_ln301_6_fu_1058_p1;
wire   [5:0] trunc_ln301_9_fu_1070_p1;
wire   [0:0] icmp_ln738_fu_1144_p2;
wire   [5:0] add_ln700_fu_1158_p2;
wire    ap_block_pp1_stage2;
wire   [0:0] icmp_ln738_1_fu_1176_p2;
wire   [5:0] add_ln700_1_fu_1190_p2;
wire   [6:0] add_ln209_fu_1263_p2;
wire   [6:0] add_ln209_1_fu_1292_p2;
wire   [31:0] zext_ln42_fu_1403_p1;
wire   [31:0] zext_ln42_2_fu_1575_p1;
wire   [31:0] zext_ln42_1_fu_1455_p1;
wire   [31:0] zext_ln42_3_fu_1633_p1;
wire   [3:0] lshr_ln_fu_962_p4;
wire   [4:0] or_ln321_fu_996_p2;
wire   [3:0] lshr_ln13_1_fu_1016_p4;
wire   [3:0] lshr_ln13_2_fu_1037_p4;
wire   [5:0] lshr_ln1_fu_1088_p4;
wire   [4:0] grp_fu_936_p4;
wire   [4:0] grp_fu_946_p4;
wire   [1:0] trunc_ln738_fu_1140_p1;
wire   [5:0] select_ln738_fu_1150_p3;
wire   [1:0] trunc_ln19_fu_1166_p1;
wire   [1:0] or_ln738_fu_1170_p2;
wire   [5:0] select_ln738_1_fu_1182_p3;
wire   [1:0] or_ln1503_fu_1198_p2;
wire   [1:0] trunc_ln1503_fu_1210_p1;
wire   [5:0] select_ln1503_fu_1242_p3;
wire   [5:0] shl_ln1503_fu_1249_p2;
wire   [6:0] zext_ln209_fu_1255_p1;
wire   [6:0] zext_ln209_1_fu_1259_p1;
wire   [5:0] select_ln1503_1_fu_1271_p3;
wire   [5:0] shl_ln1503_1_fu_1278_p2;
wire   [6:0] zext_ln209_2_fu_1284_p1;
wire   [6:0] zext_ln209_3_fu_1288_p1;
wire   [4:0] or_ln555_fu_1318_p2;
wire   [29:0] tmp_3_fu_1336_p8;
wire   [3:0] lshr_ln3_fu_1359_p4;
wire   [7:0] zext_ln555_6_fu_1387_p1;
wire   [7:0] zext_ln555_5_fu_1383_p1;
wire   [7:0] zext_ln555_4_fu_1379_p1;
wire   [30:0] tmp_7_fu_1391_p5;
wire   [29:0] tmp_4_fu_1408_p8;
wire   [7:0] zext_ln555_9_fu_1439_p1;
wire   [7:0] zext_ln555_8_fu_1435_p1;
wire   [7:0] zext_ln555_7_fu_1431_p1;
wire   [30:0] tmp_8_fu_1443_p5;
wire   [4:0] or_ln31_fu_1460_p2;
wire   [4:0] or_ln31_1_fu_1488_p2;
wire   [29:0] tmp_5_fu_1522_p8;
wire   [7:0] zext_ln555_12_fu_1559_p1;
wire   [7:0] zext_ln555_11_fu_1555_p1;
wire   [7:0] zext_ln555_10_fu_1551_p1;
wire   [30:0] tmp_9_fu_1563_p5;
wire   [29:0] tmp_6_fu_1580_p8;
wire   [7:0] zext_ln555_15_fu_1617_p1;
wire   [7:0] zext_ln555_14_fu_1613_p1;
wire   [7:0] zext_ln555_13_fu_1609_p1;
wire   [30:0] tmp_s_fu_1621_p5;
wire    ap_CS_fsm_state15;
reg   [11:0] ap_NS_fsm;
wire    ap_block_pp1_stage1_subdone;
wire    ap_block_pp1_stage2_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;

// power-on initialization
initial begin
#0 ap_CS_fsm = 12'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
end

estimate_FR_2_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
estimate_FR_2_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .inputs_0_address0(inputs_0_address0),
    .inputs_0_ce0(inputs_0_ce0),
    .inputs_0_q0(inputs_0_q0),
    .inputs_1_address0(inputs_1_address0),
    .inputs_1_ce0(inputs_1_ce0),
    .inputs_1_q0(inputs_1_q0),
    .counts_0_address0(counts_0_address0),
    .counts_0_ce0(counts_0_ce0),
    .counts_0_we0(counts_0_we0),
    .counts_0_d0(counts_0_d0),
    .counts_0_q0(counts_0_q0),
    .counts_1_address0(counts_1_address0),
    .counts_1_ce0(counts_1_ce0),
    .counts_1_we0(counts_1_we0),
    .counts_1_d0(counts_1_d0),
    .counts_1_q0(counts_1_q0),
    .outputs_0_address0(outputs_0_address0),
    .outputs_0_ce0(outputs_0_ce0),
    .outputs_0_we0(outputs_0_we0),
    .outputs_0_d0(outputs_0_d0),
    .outputs_1_address0(outputs_1_address0),
    .outputs_1_ce0(outputs_1_ce0),
    .outputs_1_we0(outputs_1_we0),
    .outputs_1_d0(outputs_1_d0)
);

estimate_FR_2_cnt_0_V #(
    .DataWidth( 6 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
cnt_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cnt_0_V_address0),
    .ce0(cnt_0_V_ce0),
    .we0(cnt_0_V_we0),
    .d0(cnt_0_V_d0),
    .q0(cnt_0_V_q0),
    .address1(cnt_0_V_address1),
    .ce1(cnt_0_V_ce1),
    .we1(cnt_0_V_we1),
    .d1(cnt_0_V_d1),
    .q1(cnt_0_V_q1)
);

estimate_FR_2_cnt_0_V #(
    .DataWidth( 6 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
cnt_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cnt_1_V_address0),
    .ce0(cnt_1_V_ce0),
    .we0(cnt_1_V_we0),
    .d0(cnt_1_V_d0),
    .q0(cnt_1_V_q0),
    .address1(cnt_1_V_address1),
    .ce1(cnt_1_V_ce1),
    .we1(cnt_1_V_we1),
    .d1(cnt_1_V_d1),
    .q1(cnt_1_V_q1)
);

estimate_FR_2_cnt_0_V #(
    .DataWidth( 6 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
cnt_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cnt_2_V_address0),
    .ce0(cnt_2_V_ce0),
    .we0(cnt_2_V_we0),
    .d0(cnt_2_V_d0),
    .q0(cnt_2_V_q0),
    .address1(cnt_2_V_address1),
    .ce1(cnt_2_V_ce1),
    .we1(cnt_2_V_we1),
    .d1(cnt_2_V_d1),
    .q1(cnt_2_V_q1)
);

estimate_FR_2_cnt_0_V #(
    .DataWidth( 6 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
cnt_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cnt_3_V_address0),
    .ce0(cnt_3_V_ce0),
    .we0(cnt_3_V_we0),
    .d0(cnt_3_V_d0),
    .q0(cnt_3_V_q0),
    .address1(cnt_3_V_address1),
    .ce1(cnt_3_V_ce1),
    .we1(cnt_3_V_we1),
    .d1(cnt_3_V_d1),
    .q1(cnt_3_V_q1)
);

estimate_FR_2_FR_0_V #(
    .DataWidth( 7 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
FR_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(FR_0_V_address0),
    .ce0(FR_0_V_ce0),
    .we0(FR_0_V_we0),
    .d0(add_ln209_fu_1263_p2),
    .q0(FR_0_V_q0),
    .address1(FR_0_V_address1),
    .ce1(FR_0_V_ce1),
    .q1(FR_0_V_q1)
);

estimate_FR_2_FR_0_V #(
    .DataWidth( 7 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
FR_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(FR_1_V_address0),
    .ce0(FR_1_V_ce0),
    .we0(FR_1_V_we0),
    .d0(add_ln209_1_fu_1292_p2),
    .q0(FR_1_V_q0),
    .address1(FR_1_V_address1),
    .ce1(FR_1_V_ce1),
    .q1(FR_1_V_q1)
);

estimate_FR_2_FR_0_V #(
    .DataWidth( 7 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
FR_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(FR_2_V_address0),
    .ce0(FR_2_V_ce0),
    .we0(FR_2_V_we0),
    .d0(add_ln209_fu_1263_p2),
    .q0(FR_2_V_q0),
    .address1(FR_2_V_address1),
    .ce1(FR_2_V_ce1),
    .q1(FR_2_V_q1)
);

estimate_FR_2_FR_0_V #(
    .DataWidth( 7 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
FR_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(FR_3_V_address0),
    .ce0(FR_3_V_ce0),
    .we0(FR_3_V_we0),
    .d0(add_ln209_1_fu_1292_p2),
    .q0(FR_3_V_q0),
    .address1(FR_3_V_address1),
    .ce1(FR_3_V_ce1),
    .q1(FR_3_V_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state6) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp1_stage3_subdone) & (1'b1 == ap_CS_fsm_pp1_stage3)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_enable_reg_pp1_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state12) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp2_stage1_subdone) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
            ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_enable_reg_pp2_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_0_reg_846 <= 7'd0;
    end else if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln19_reg_1677 == 1'd0))) begin
        i_0_0_reg_846 <= add_ln19_reg_1792;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0))) begin
        j_0_0_reg_822 <= add_ln12_reg_1672;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        j_0_0_reg_822 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        k_0_0_reg_858 <= 5'd0;
    end else if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln31_reg_1797 == 1'd0))) begin
        k_0_0_reg_858 <= add_ln31_reg_1971;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (tmp_10_reg_1695 == 1'd1) & (icmp_ln19_reg_1677 == 1'd0))) begin
        FR_0_V_addr_2_reg_1760 <= zext_ln1503_fu_1214_p1;
        FR_2_V_addr_2_reg_1765 <= zext_ln1503_fu_1214_p1;
        cnt_0_V_addr_9_reg_1743 <= zext_ln1503_fu_1214_p1;
        cnt_2_V_addr_9_reg_1749 <= zext_ln1503_fu_1214_p1;
        icmp_ln1503_reg_1755 <= icmp_ln1503_fu_1222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (tmp_11_reg_1715 == 1'd1) & (icmp_ln19_reg_1677 == 1'd0))) begin
        FR_1_V_addr_4_reg_1782 <= zext_ln1503_1_fu_1228_p1;
        FR_3_V_addr_4_reg_1787 <= zext_ln1503_1_fu_1228_p1;
        cnt_1_V_addr_9_reg_1770 <= zext_ln1503_1_fu_1228_p1;
        cnt_3_V_addr_9_reg_1776 <= zext_ln1503_1_fu_1228_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0))) begin
        add_ln12_reg_1672 <= add_ln12_fu_1052_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln19_reg_1677 == 1'd0))) begin
        add_ln19_reg_1792 <= add_ln19_fu_1236_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0))) begin
        add_ln31_reg_1971 <= add_ln31_fu_1516_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001) & (trunc_ln301_11_fu_1104_p1 == 1'd1) & (icmp_ln19_reg_1677 == 1'd0))) begin
        cnt_0_V_addr_5_reg_1699 <= zext_ln738_fu_1116_p1;
        cnt_2_V_addr_5_reg_1705 <= zext_ln738_fu_1116_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (trunc_ln301_12_fu_1122_p1 == 1'd1) & (1'b0 == ap_block_pp1_stage1_11001) & (icmp_ln19_reg_1677 == 1'd0))) begin
        cnt_1_V_addr_8_reg_1720 <= zext_ln738_1_fu_1134_p1;
        cnt_3_V_addr_8_reg_1726 <= zext_ln738_1_fu_1134_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln12_reg_1638 <= icmp_ln12_fu_956_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (tmp_11_reg_1715 == 1'd1) & (icmp_ln19_reg_1677 == 1'd0))) begin
        icmp_ln1503_1_reg_1738 <= icmp_ln1503_1_fu_1204_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        icmp_ln19_reg_1677 <= icmp_ln19_fu_1082_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln31_reg_1797 <= icmp_ln31_fu_1300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0))) begin
        lshr_ln36_1_reg_1901 <= {{or_ln31_fu_1460_p2[4:1]}};
        lshr_ln36_2_reg_1946 <= {{or_ln31_1_fu_1488_p2[4:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0))) begin
        or_ln12_1_reg_1662[4 : 2] <= or_ln12_1_fu_1031_p2[4 : 2];
        or_ln12_reg_1652[0] <= or_ln12_fu_1010_p2[0];
or_ln12_reg_1652[4 : 2] <= or_ln12_fu_1010_p2[4 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln19_reg_1677 == 1'd0))) begin
        p_090_0217_0_reg_834 <= tmp_11_reg_1715;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001) & (icmp_ln19_reg_1677 == 1'd0))) begin
        tmp_10_reg_1695 <= inputs_0_q0[32'd1];
        trunc_ln301_11_reg_1691 <= trunc_ln301_11_fu_1104_p1;
        trunc_ln301_12_reg_1711 <= trunc_ln301_12_fu_1122_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001) & (icmp_ln19_reg_1677 == 1'd0))) begin
        tmp_11_reg_1715 <= inputs_1_q0[32'd1];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        FR_0_V_address0 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        FR_0_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        FR_0_V_address0 = FR_0_V_addr_2_reg_1760;
    end else begin
        FR_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp2_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            FR_0_V_address1 = zext_ln555_2_fu_1466_p1;
        end else if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            FR_0_V_address1 = zext_ln555_1_fu_1324_p1;
        end else begin
            FR_0_V_address1 = 'bx;
        end
    end else begin
        FR_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        FR_0_V_ce0 = 1'b1;
    end else begin
        FR_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        FR_0_V_ce1 = 1'b1;
    end else begin
        FR_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln1503_reg_1755 == 1'd1) & (tmp_10_reg_1695 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        FR_0_V_we0 = 1'b1;
    end else begin
        FR_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        FR_1_V_address0 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        FR_1_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        FR_1_V_address0 = FR_1_V_addr_4_reg_1782;
    end else begin
        FR_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp2_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            FR_1_V_address1 = zext_ln555_2_fu_1466_p1;
        end else if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            FR_1_V_address1 = zext_ln555_1_fu_1324_p1;
        end else begin
            FR_1_V_address1 = 'bx;
        end
    end else begin
        FR_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        FR_1_V_ce0 = 1'b1;
    end else begin
        FR_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        FR_1_V_ce1 = 1'b1;
    end else begin
        FR_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln1503_1_reg_1738 == 1'd1) & (tmp_11_reg_1715 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        FR_1_V_we0 = 1'b1;
    end else begin
        FR_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        FR_2_V_address0 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        FR_2_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        FR_2_V_address0 = FR_2_V_addr_2_reg_1765;
    end else begin
        FR_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp2_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            FR_2_V_address1 = zext_ln555_2_fu_1466_p1;
        end else if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            FR_2_V_address1 = zext_ln555_1_fu_1324_p1;
        end else begin
            FR_2_V_address1 = 'bx;
        end
    end else begin
        FR_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        FR_2_V_ce0 = 1'b1;
    end else begin
        FR_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        FR_2_V_ce1 = 1'b1;
    end else begin
        FR_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_10_reg_1695 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln1503_reg_1755 == 1'd0))) begin
        FR_2_V_we0 = 1'b1;
    end else begin
        FR_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        FR_3_V_address0 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        FR_3_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        FR_3_V_address0 = FR_3_V_addr_4_reg_1787;
    end else begin
        FR_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp2_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp2_stage1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
            FR_3_V_address1 = zext_ln555_2_fu_1466_p1;
        end else if (((1'b0 == ap_block_pp2_stage0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            FR_3_V_address1 = zext_ln555_1_fu_1324_p1;
        end else begin
            FR_3_V_address1 = 'bx;
        end
    end else begin
        FR_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        FR_3_V_ce0 = 1'b1;
    end else begin
        FR_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        FR_3_V_ce1 = 1'b1;
    end else begin
        FR_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_11_reg_1715 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln1503_1_reg_1738 == 1'd0))) begin
        FR_3_V_we0 = 1'b1;
    end else begin
        FR_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln12_fu_956_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln19_fu_1082_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state6 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state6 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln31_fu_1300_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state12 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln19_reg_1677 == 1'd0))) begin
        ap_phi_mux_i_0_0_phi_fu_850_p4 = add_ln19_reg_1792;
    end else begin
        ap_phi_mux_i_0_0_phi_fu_850_p4 = i_0_0_reg_846;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln12_reg_1638 == 1'd0))) begin
        ap_phi_mux_j_0_0_phi_fu_826_p4 = add_ln12_reg_1672;
    end else begin
        ap_phi_mux_j_0_0_phi_fu_826_p4 = j_0_0_reg_822;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (icmp_ln31_reg_1797 == 1'd0))) begin
        ap_phi_mux_k_0_0_phi_fu_862_p4 = add_ln31_reg_1971;
    end else begin
        ap_phi_mux_k_0_0_phi_fu_862_p4 = k_0_0_reg_858;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_0_V_address0 = zext_ln555_2_fu_1466_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_0_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_0_V_address0 = cnt_0_V_addr_9_reg_1743;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_0_V_address0 = cnt_0_V_addr_5_reg_1699;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_0_V_address0 = zext_ln321_2_fu_1063_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_0_V_address0 = zext_ln321_fu_983_p1;
    end else begin
        cnt_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_0_V_address1 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_0_V_address1 = zext_ln555_1_fu_1324_p1;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_0_V_address1 = zext_ln1503_fu_1214_p1;
    end else if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        cnt_0_V_address1 = zext_ln738_fu_1116_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_0_V_address1 = zext_ln321_3_fu_1075_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_0_V_address1 = zext_ln321_1_fu_1002_p1;
    end else begin
        cnt_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_0_V_ce0 = 1'b1;
    end else begin
        cnt_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_0_V_ce1 = 1'b1;
    end else begin
        cnt_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_0_V_d0 = 6'd0;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_0_V_d0 = add_ln700_fu_1158_p2;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_0_V_d0 = trunc_ln301_6_fu_1058_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_0_V_d0 = trunc_ln301_fu_978_p1;
    end else begin
        cnt_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_0_V_d1 = trunc_ln301_9_fu_1070_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_0_V_d1 = trunc_ln301_3_fu_991_p1;
    end else begin
        cnt_0_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln738_fu_1144_p2 == 1'd1) & (trunc_ln301_11_reg_1691 == 1'd1) & (icmp_ln19_reg_1677 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln1503_reg_1755 == 1'd1) & (tmp_10_reg_1695 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_0_V_we0 = 1'b1;
    end else begin
        cnt_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_0_V_we1 = 1'b1;
    end else begin
        cnt_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_1_V_address0 = zext_ln555_2_fu_1466_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_1_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_1_V_address0 = cnt_1_V_addr_9_reg_1770;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_1_V_address0 = cnt_1_V_addr_8_reg_1720;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_1_V_address0 = zext_ln321_2_fu_1063_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_1_V_address0 = zext_ln321_fu_983_p1;
    end else begin
        cnt_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_1_V_address1 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_1_V_address1 = zext_ln555_1_fu_1324_p1;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_1_V_address1 = zext_ln1503_1_fu_1228_p1;
    end else if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        cnt_1_V_address1 = zext_ln738_1_fu_1134_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_1_V_address1 = zext_ln321_3_fu_1075_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_1_V_address1 = zext_ln321_1_fu_1002_p1;
    end else begin
        cnt_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_1_V_ce0 = 1'b1;
    end else begin
        cnt_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_1_V_ce1 = 1'b1;
    end else begin
        cnt_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_1_V_d0 = 6'd0;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_1_V_d0 = add_ln700_1_fu_1190_p2;
    end else if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cnt_1_V_d0 = {{counts_0_q0[13:8]}};
    end else begin
        cnt_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln738_1_fu_1176_p2 == 1'd1) & (trunc_ln301_12_reg_1711 == 1'd1) & (icmp_ln19_reg_1677 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln1503_1_reg_1738 == 1'd1) & (tmp_11_reg_1715 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_1_V_we0 = 1'b1;
    end else begin
        cnt_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_1_V_we1 = 1'b1;
    end else begin
        cnt_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_2_V_address0 = zext_ln555_2_fu_1466_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_2_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_2_V_address0 = cnt_2_V_addr_9_reg_1749;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_2_V_address0 = cnt_2_V_addr_5_reg_1705;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_2_V_address0 = zext_ln321_2_fu_1063_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_2_V_address0 = zext_ln321_fu_983_p1;
    end else begin
        cnt_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_2_V_address1 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_2_V_address1 = zext_ln555_1_fu_1324_p1;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_2_V_address1 = zext_ln1503_fu_1214_p1;
    end else if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        cnt_2_V_address1 = zext_ln738_fu_1116_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_2_V_address1 = zext_ln321_3_fu_1075_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_2_V_address1 = zext_ln321_1_fu_1002_p1;
    end else begin
        cnt_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_2_V_ce0 = 1'b1;
    end else begin
        cnt_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_2_V_ce1 = 1'b1;
    end else begin
        cnt_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_2_V_d0 = 6'd0;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_2_V_d0 = add_ln700_fu_1158_p2;
    end else if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cnt_2_V_d0 = {{counts_0_q0[21:16]}};
    end else begin
        cnt_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1) & (trunc_ln301_11_reg_1691 == 1'd1) & (icmp_ln738_fu_1144_p2 == 1'd0) & (icmp_ln19_reg_1677 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_10_reg_1695 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln1503_reg_1755 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_2_V_we0 = 1'b1;
    end else begin
        cnt_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_2_V_we1 = 1'b1;
    end else begin
        cnt_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_3_V_address0 = zext_ln555_2_fu_1466_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_3_V_address0 = zext_ln555_fu_1306_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_3_V_address0 = cnt_3_V_addr_9_reg_1776;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_3_V_address0 = cnt_3_V_addr_8_reg_1726;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_3_V_address0 = zext_ln321_2_fu_1063_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_3_V_address0 = zext_ln321_fu_983_p1;
    end else begin
        cnt_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        cnt_3_V_address1 = zext_ln555_3_fu_1494_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        cnt_3_V_address1 = zext_ln555_1_fu_1324_p1;
    end else if (((1'b0 == ap_block_pp1_stage3) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_3_V_address1 = zext_ln1503_1_fu_1228_p1;
    end else if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        cnt_3_V_address1 = zext_ln738_1_fu_1134_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cnt_3_V_address1 = zext_ln321_3_fu_1075_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        cnt_3_V_address1 = zext_ln321_1_fu_1002_p1;
    end else begin
        cnt_3_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_3_V_ce0 = 1'b1;
    end else begin
        cnt_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter0 == 1'b1)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (1'b0 == ap_block_pp1_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        cnt_3_V_ce1 = 1'b1;
    end else begin
        cnt_3_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        cnt_3_V_d0 = 6'd0;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        cnt_3_V_d0 = add_ln700_1_fu_1190_p2;
    end else if ((((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        cnt_3_V_d0 = {{counts_0_q0[29:24]}};
    end else begin
        cnt_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1) & (trunc_ln301_12_reg_1711 == 1'd1) & (icmp_ln738_1_fu_1176_p2 == 1'd0) & (icmp_ln19_reg_1677 == 1'd0)) | ((ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_11_reg_1715 == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln1503_1_reg_1738 == 1'd0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_3_V_we0 = 1'b1;
    end else begin
        cnt_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (icmp_ln12_reg_1638 == 1'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln12_reg_1638 == 1'd0)))) begin
        cnt_3_V_we1 = 1'b1;
    end else begin
        cnt_3_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        counts_0_address0 = zext_ln36_4_fu_1545_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        counts_0_address0 = zext_ln36_1_fu_1369_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        counts_0_address0 = zext_ln13_1_fu_1026_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counts_0_address0 = zext_ln13_fu_972_p1;
    end else begin
        counts_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        counts_0_ce0 = 1'b1;
    end else begin
        counts_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        counts_0_d0 = zext_ln36_3_fu_1540_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        counts_0_d0 = zext_ln36_fu_1354_p1;
    end else begin
        counts_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        counts_0_we0 = 1'b1;
    end else begin
        counts_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        counts_1_address0 = zext_ln36_6_fu_1603_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        counts_1_address0 = zext_ln36_1_fu_1369_p1;
    end else if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        counts_1_address0 = zext_ln13_2_fu_1047_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        counts_1_address0 = zext_ln13_fu_972_p1;
    end else begin
        counts_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        counts_1_ce0 = 1'b1;
    end else begin
        counts_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        counts_1_d0 = zext_ln36_5_fu_1598_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        counts_1_d0 = zext_ln36_2_fu_1426_p1;
    end else begin
        counts_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)))) begin
        counts_1_we0 = 1'b1;
    end else begin
        counts_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        inputs_0_ce0 = 1'b1;
    end else begin
        inputs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        inputs_1_ce0 = 1'b1;
    end else begin
        inputs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_0_address0 = outputs_0_addr_2_gep_fu_790_p3;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0))) begin
        outputs_0_address0 = zext_ln36_4_fu_1545_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_0_address0 = outputs_0_addr_gep_fu_624_p3;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0))) begin
        outputs_0_address0 = zext_ln36_1_fu_1369_p1;
    end else begin
        outputs_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1)))) begin
        outputs_0_ce0 = 1'b1;
    end else begin
        outputs_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_0_d0 = zext_ln42_2_fu_1575_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_0_d0 = zext_ln42_fu_1403_p1;
    end else if ((((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0)))) begin
        outputs_0_d0 = 32'd1;
    end else begin
        outputs_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1)))) begin
        outputs_0_we0 = 1'b1;
    end else begin
        outputs_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_1_address0 = outputs_1_addr_2_gep_fu_814_p3;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0))) begin
        outputs_1_address0 = zext_ln36_6_fu_1603_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_1_address0 = outputs_1_addr_gep_fu_654_p3;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0))) begin
        outputs_1_address0 = zext_ln36_1_fu_1369_p1;
    end else begin
        outputs_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1)))) begin
        outputs_1_ce0 = 1'b1;
    end else begin
        outputs_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_1_d0 = zext_ln42_3_fu_1633_p1;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1))) begin
        outputs_1_d0 = zext_ln42_1_fu_1455_p1;
    end else if ((((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0)))) begin
        outputs_1_d0 = 32'd1;
    end else begin
        outputs_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1) & (icmp_ln31_reg_1797 == 1'd0) & (p_090_0217_0_reg_834 == 1'd1)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd0)) | ((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (p_090_0217_0_reg_834 == 1'd1)))) begin
        outputs_1_we0 = 1'b1;
    end else begin
        outputs_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln12_fu_956_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln12_fu_956_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln19_fu_1082_p2 == 1'd1)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter0 == 1'b1) & (icmp_ln19_fu_1082_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((1'b0 == ap_block_pp1_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp1_stage3 : begin
            if ((1'b0 == ap_block_pp1_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln31_fu_1300_p2 == 1'd1)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter0 == 1'b1) & (icmp_ln31_fu_1300_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln12_fu_1052_p2 = (5'd4 + j_0_0_reg_822);

assign add_ln19_fu_1236_p2 = (i_0_0_reg_846 + 7'd2);

assign add_ln209_1_fu_1292_p2 = (zext_ln209_2_fu_1284_p1 + zext_ln209_3_fu_1288_p1);

assign add_ln209_fu_1263_p2 = (zext_ln209_fu_1255_p1 + zext_ln209_1_fu_1259_p1);

assign add_ln31_fu_1516_p2 = (k_0_0_reg_858 + 5'd4);

assign add_ln700_1_fu_1190_p2 = (select_ln738_1_fu_1182_p3 + 6'd1);

assign add_ln700_fu_1158_p2 = (6'd1 + select_ln738_fu_1150_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp1_stage3 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp2_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cnt_1_V_d1 = {{counts_1_q0[13:8]}};

assign cnt_2_V_d1 = {{counts_1_q0[21:16]}};

assign cnt_3_V_d1 = {{counts_1_q0[29:24]}};

assign grp_fu_936_p4 = {{i_0_0_reg_846[6:2]}};

assign grp_fu_946_p4 = {{i_0_0_reg_846[6:2]}};

assign icmp_ln12_fu_956_p2 = ((ap_phi_mux_j_0_0_phi_fu_826_p4 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln1503_1_fu_1204_p2 = ((or_ln1503_fu_1198_p2 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln1503_fu_1222_p2 = ((trunc_ln1503_fu_1210_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_1082_p2 = ((ap_phi_mux_i_0_0_phi_fu_850_p4 == 7'd96) ? 1'b1 : 1'b0);

assign icmp_ln31_fu_1300_p2 = ((ap_phi_mux_k_0_0_phi_fu_862_p4 == 5'd24) ? 1'b1 : 1'b0);

assign icmp_ln738_1_fu_1176_p2 = ((or_ln738_fu_1170_p2 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln738_fu_1144_p2 = ((trunc_ln738_fu_1140_p1 == 2'd0) ? 1'b1 : 1'b0);

assign inputs_0_address0 = zext_ln20_fu_1098_p1;

assign inputs_1_address0 = zext_ln20_fu_1098_p1;

assign lshr_ln13_1_fu_1016_p4 = {{or_ln12_fu_1010_p2[4:1]}};

assign lshr_ln13_2_fu_1037_p4 = {{or_ln12_1_fu_1031_p2[4:1]}};

assign lshr_ln1_fu_1088_p4 = {{ap_phi_mux_i_0_0_phi_fu_850_p4[6:1]}};

assign lshr_ln3_fu_1359_p4 = {{k_0_0_reg_858[4:1]}};

assign lshr_ln_fu_962_p4 = {{ap_phi_mux_j_0_0_phi_fu_826_p4[4:1]}};

assign or_ln12_1_fu_1031_p2 = (j_0_0_reg_822 | 5'd3);

assign or_ln12_fu_1010_p2 = (j_0_0_reg_822 | 5'd2);

assign or_ln1503_fu_1198_p2 = (trunc_ln19_fu_1166_p1 | 2'd1);

assign or_ln31_1_fu_1488_p2 = (k_0_0_reg_858 | 5'd3);

assign or_ln31_fu_1460_p2 = (k_0_0_reg_858 | 5'd2);

assign or_ln321_fu_996_p2 = (j_0_0_reg_822 | 5'd1);

assign or_ln555_fu_1318_p2 = (ap_phi_mux_k_0_0_phi_fu_862_p4 | 5'd1);

assign or_ln738_fu_1170_p2 = (trunc_ln19_fu_1166_p1 | 2'd1);

assign outputs_0_addr_2_gep_fu_790_p3 = zext_ln36_4_fu_1545_p1;

assign outputs_0_addr_gep_fu_624_p3 = zext_ln36_1_fu_1369_p1;

assign outputs_1_addr_2_gep_fu_814_p3 = zext_ln36_6_fu_1603_p1;

assign outputs_1_addr_gep_fu_654_p3 = zext_ln36_1_fu_1369_p1;

assign select_ln1503_1_fu_1271_p3 = ((icmp_ln1503_1_reg_1738[0:0] === 1'b1) ? cnt_1_V_q1 : cnt_3_V_q1);

assign select_ln1503_fu_1242_p3 = ((icmp_ln1503_reg_1755[0:0] === 1'b1) ? cnt_0_V_q1 : cnt_2_V_q1);

assign select_ln738_1_fu_1182_p3 = ((icmp_ln738_1_fu_1176_p2[0:0] === 1'b1) ? cnt_1_V_q1 : cnt_3_V_q1);

assign select_ln738_fu_1150_p3 = ((icmp_ln738_fu_1144_p2[0:0] === 1'b1) ? cnt_0_V_q1 : cnt_2_V_q1);

assign shl_ln1503_1_fu_1278_p2 = select_ln1503_1_fu_1271_p3 << 6'd2;

assign shl_ln1503_fu_1249_p2 = select_ln1503_fu_1242_p3 << 6'd2;

assign tmp_3_fu_1336_p8 = {{{{{{{cnt_3_V_q0}, {2'd0}}, {cnt_2_V_q0}}, {2'd0}}, {cnt_1_V_q0}}, {2'd0}}, {cnt_0_V_q0}};

assign tmp_4_fu_1408_p8 = {{{{{{{cnt_3_V_q1}, {2'd0}}, {cnt_2_V_q1}}, {2'd0}}, {cnt_1_V_q1}}, {2'd0}}, {cnt_0_V_q1}};

assign tmp_5_fu_1522_p8 = {{{{{{{cnt_3_V_q0}, {2'd0}}, {cnt_2_V_q0}}, {2'd0}}, {cnt_1_V_q0}}, {2'd0}}, {cnt_0_V_q0}};

assign tmp_6_fu_1580_p8 = {{{{{{{cnt_3_V_q1}, {2'd0}}, {cnt_2_V_q1}}, {2'd0}}, {cnt_1_V_q1}}, {2'd0}}, {cnt_0_V_q1}};

assign tmp_7_fu_1391_p5 = {{{{FR_3_V_q0}, {zext_ln555_6_fu_1387_p1}}, {zext_ln555_5_fu_1383_p1}}, {zext_ln555_4_fu_1379_p1}};

assign tmp_8_fu_1443_p5 = {{{{FR_3_V_q1}, {zext_ln555_9_fu_1439_p1}}, {zext_ln555_8_fu_1435_p1}}, {zext_ln555_7_fu_1431_p1}};

assign tmp_9_fu_1563_p5 = {{{{FR_3_V_q1}, {zext_ln555_12_fu_1559_p1}}, {zext_ln555_11_fu_1555_p1}}, {zext_ln555_10_fu_1551_p1}};

assign tmp_s_fu_1621_p5 = {{{{FR_3_V_q0}, {zext_ln555_15_fu_1617_p1}}, {zext_ln555_14_fu_1613_p1}}, {zext_ln555_13_fu_1609_p1}};

assign trunc_ln1503_fu_1210_p1 = i_0_0_reg_846[1:0];

assign trunc_ln19_fu_1166_p1 = i_0_0_reg_846[1:0];

assign trunc_ln301_11_fu_1104_p1 = inputs_0_q0[0:0];

assign trunc_ln301_12_fu_1122_p1 = inputs_1_q0[0:0];

assign trunc_ln301_3_fu_991_p1 = counts_1_q0[5:0];

assign trunc_ln301_6_fu_1058_p1 = counts_0_q0[5:0];

assign trunc_ln301_9_fu_1070_p1 = counts_1_q0[5:0];

assign trunc_ln301_fu_978_p1 = counts_0_q0[5:0];

assign trunc_ln738_fu_1140_p1 = i_0_0_reg_846[1:0];

assign zext_ln13_1_fu_1026_p1 = lshr_ln13_1_fu_1016_p4;

assign zext_ln13_2_fu_1047_p1 = lshr_ln13_2_fu_1037_p4;

assign zext_ln13_fu_972_p1 = lshr_ln_fu_962_p4;

assign zext_ln1503_1_fu_1228_p1 = grp_fu_946_p4;

assign zext_ln1503_fu_1214_p1 = grp_fu_936_p4;

assign zext_ln209_1_fu_1259_p1 = select_ln1503_fu_1242_p3;

assign zext_ln209_2_fu_1284_p1 = shl_ln1503_1_fu_1278_p2;

assign zext_ln209_3_fu_1288_p1 = select_ln1503_1_fu_1271_p3;

assign zext_ln209_fu_1255_p1 = shl_ln1503_fu_1249_p2;

assign zext_ln20_fu_1098_p1 = lshr_ln1_fu_1088_p4;

assign zext_ln321_1_fu_1002_p1 = or_ln321_fu_996_p2;

assign zext_ln321_2_fu_1063_p1 = or_ln12_reg_1652;

assign zext_ln321_3_fu_1075_p1 = or_ln12_1_reg_1662;

assign zext_ln321_fu_983_p1 = j_0_0_reg_822;

assign zext_ln36_1_fu_1369_p1 = lshr_ln3_fu_1359_p4;

assign zext_ln36_2_fu_1426_p1 = tmp_4_fu_1408_p8;

assign zext_ln36_3_fu_1540_p1 = tmp_5_fu_1522_p8;

assign zext_ln36_4_fu_1545_p1 = lshr_ln36_1_reg_1901;

assign zext_ln36_5_fu_1598_p1 = tmp_6_fu_1580_p8;

assign zext_ln36_6_fu_1603_p1 = lshr_ln36_2_reg_1946;

assign zext_ln36_fu_1354_p1 = tmp_3_fu_1336_p8;

assign zext_ln42_1_fu_1455_p1 = tmp_8_fu_1443_p5;

assign zext_ln42_2_fu_1575_p1 = tmp_9_fu_1563_p5;

assign zext_ln42_3_fu_1633_p1 = tmp_s_fu_1621_p5;

assign zext_ln42_fu_1403_p1 = tmp_7_fu_1391_p5;

assign zext_ln555_10_fu_1551_p1 = FR_0_V_q1;

assign zext_ln555_11_fu_1555_p1 = FR_1_V_q1;

assign zext_ln555_12_fu_1559_p1 = FR_2_V_q1;

assign zext_ln555_13_fu_1609_p1 = FR_0_V_q0;

assign zext_ln555_14_fu_1613_p1 = FR_1_V_q0;

assign zext_ln555_15_fu_1617_p1 = FR_2_V_q0;

assign zext_ln555_1_fu_1324_p1 = or_ln555_fu_1318_p2;

assign zext_ln555_2_fu_1466_p1 = or_ln31_fu_1460_p2;

assign zext_ln555_3_fu_1494_p1 = or_ln31_1_fu_1488_p2;

assign zext_ln555_4_fu_1379_p1 = FR_0_V_q0;

assign zext_ln555_5_fu_1383_p1 = FR_1_V_q0;

assign zext_ln555_6_fu_1387_p1 = FR_2_V_q0;

assign zext_ln555_7_fu_1431_p1 = FR_0_V_q1;

assign zext_ln555_8_fu_1435_p1 = FR_1_V_q1;

assign zext_ln555_9_fu_1439_p1 = FR_2_V_q1;

assign zext_ln555_fu_1306_p1 = ap_phi_mux_k_0_0_phi_fu_862_p4;

assign zext_ln738_1_fu_1134_p1 = grp_fu_946_p4;

assign zext_ln738_fu_1116_p1 = grp_fu_936_p4;

always @ (posedge ap_clk) begin
    or_ln12_reg_1652[1] <= 1'b1;
    or_ln12_1_reg_1662[1:0] <= 2'b11;
end

endmodule //estimate_FR_2
